import type { Metadata } from "next";
// import { Inter } from 'next/font/google'
import "./globals.css";

import { ThemeProvider } from "@/components/theme-provider";
import "@radix-ui/themes/styles.css";
import { Theme } from "@radix-ui/themes";
import { ToastContainer } from "react-toastify";

import NextAuthProvider from "./Providers";
//const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Theme>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <NextAuthProvider>{children}</NextAuthProvider>
            <ToastContainer position="bottom-right" />
          </ThemeProvider>
        </Theme>
      </body>
    </html>
  );
}
